name: test-all
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    permissions: 
      statuses: write
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -L -X POST  https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             -d "{\"state\":\"pending\", \"context\":\"Jenkins CI\"}"
        
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Sleeping
        run: sleep 5
